### ISSUE TITLE
All that happens when I click 'Sync now', is the program window 'glows' momentarily, but never opens Imgur in my browser as expected

### ISSUE THREAD

**Issue by steve-davey** [LenAnderson/Syncurr#6]
I tried it on Windows 10 Pro, 64-bit v21H2, with Firefox as my default browser, but all that happens when I click 'Sync now', is the program window 'glows' momentarily, but never opens Imgur in my browser as expected.

**Comment by LenAnderson** [comment]
I can replicate this issue if I start with a fresh copy of Syncurr. Not sure why, but it seems to fix itself if I first click on Log Out and then on Sync Now.

**Comment by steve-davey** [comment]
> I can replicate this issue if I start with a fresh copy of Syncurr. Not sure why, but it seems to fix itself if I first click on Log Out and then on Sync Now.

Thanks. I tried that, but just got the same behaviour. I tried disabling all my browser add-ons including ad blocker, but to no avail.

**Comment by LenAnderson** [comment]
1. Do you have any albums or users added to be synced?
2. Do you have the checkbox for "Sync my account" ticked?
3. Did you enter a path for "My account directory"?

**Comment by steve-davey** [comment]
> 1. Do you have any albums or users added to be synced?
> 
>     2. Do you have the checkbox for "Sync my account" ticked?
> 
>     3. Did you enter a path for "My account directory"?

No to all those questions.

Edit: ah, I think I've got it now. It seems you have to do at least one of those things before it has any tasks to prompt it to open the browser? It does appear to have synced an album, though it immediately closed, so I wasn't sure what it had done.

Edit2: no, it looks like the sync has not completed successfully.

Edit3: tried it a couple of times, but it crashes after uploading 2 images.

**Comment by LenAnderson** [comment]
Hm, yea, I think a connection to imgur is only established when there is anything to sync, so without at least one of those the app won't even realize that it is not authorized yet.

I'm not sure why it still fails now. I seem to be able to upload and download without issue.  
Does Syncurr just close without warning, or do you get any error messages first? Anything about the appcrash in Windows Event Viewer (usually in "Windows Logs" --> "Application")?

I haven't touched this application (neither the code or even just using it) in a long, long time so it may take me a while to figure out what exactly is going on :D

**Comment by steve-davey** [comment]
> I'm not sure why it still fails now. I seem to be able to upload and download without issue. Does Syncurr just close without warning, or do you get any error messages first? Anything about the appcrash in Windows Event Viewer (usually in "Windows Logs" --> "Application")?

OK, so I tried it with Event Viewer open and this is the error:

Application: Syncurr.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException
   at MahApps.Metro.Controls.Dialogs.DialogCoordinator.GetMetroWindow(System.Object)
   at MahApps.Metro.Controls.Dialogs.DialogCoordinator.ShowMessageAsync(System.Object, System.String, System.String, MahApps.Metro.Controls.Dialogs.MessageDialogStyle, MahApps.Metro.Controls.Dialogs.MetroDialogSettings)
   at SyncurrWPF.ViewModels.AlbumListViewModel+<DoSync>d__9.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at SyncurrWPF.ViewModels.SyncViewModel+<Sync>d__0.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at SyncurrWPF.ViewModels.AppViewModel+<DoSync>d__30.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at SyncurrWPF.ViewModels.AppViewModel+<<get_SyncCommand>b__36_0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run(System.Windows.Window)
   at SyncurrWPF.App.Main(System.String[])

Faulting application name: Syncurr.exe, version: 2.2.0.0, time stamp: 0x5e46aa76
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1526, time stamp: 0xd9a6be6b
Exception code: 0xe0434352
Fault offset: 0x0012b812
Faulting process ID: 0x143c
Faulting application start time: 0x01d8228547e4b9a1
Faulting application path: D:\DOWNLOADS\SOFTWARE\Syncurr-v2.2.0\Syncurr\Syncurr.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report ID: 50c0be6e-876e-4087-b779-72a505a86ab7
Faulting package full name: 
Faulting package-relative application ID: 
![Capture14](https://user-images.githubusercontent.com/42737000/154101843-29287ad5-a3af-4c71-aef3-9d8dfdb121a4.JPG)
![Capture15](https://user-images.githubusercontent.com/42737000/154101856-60d7e8fc-4e3a-49c7-9d69-5638406e0be3.JPG)
![Capture16](https://user-images.githubusercontent.com/42737000/154101872-01f96a26-a712-42ec-b14a-696e339b44a0.JPG)
![Capture17](https://user-images.githubusercontent.com/42737000/154101883-9f5a615d-2975-4eb6-883c-e540a4083b4e.JPG)

**Comment by LenAnderson** [comment]
Ok, that helped. I think (hope) I found the issue and a fix.  
Are you on the "Album" tab when clicking on Sync Now? If not, does it still crash if you are on the "Album" tab when clicking on Sync Now?

It probably still won't sync because the crash happens when Syncurr tries to show an error message saying that a sync failed, but at least we'd be one step closer if this is it.

**Comment by steve-davey** [comment]
> Are you on the "Album" tab when clicking on Sync Now? If not, does it still crash if you are on the "Album" tab when clicking on Sync Now?

I tried it on three different tabs but it crashed every time. I can see that it has managed to upload two files each time. Funnily enough, those files are already in the remote folder, so I don't know what it is trying to upload those files for in the first place. If it was doing what I want it to do, it would recognise that those files are already present in the remote folder, and skip them.

**Comment by LenAnderson** [comment]
Could you give v2.3.0 a try and let me know if it works better?

https://github.com/LenAnderson/Syncurr/releases/tag/v2.3.0

**Comment by steve-davey** [comment]
> Could you give v2.3.0 a try and let me know if it works better?
> 
> https://github.com/LenAnderson/Syncurr/releases/tag/v2.3.0

Thanks, that is a lot better. It didn't crash at all this time. The only issue was it 'complained' about not finding a certain image locally, so I renamed the image in question to match what it was looking for, and that did the trick. 

![Syncurr](https://user-images.githubusercontent.com/42737000/154686120-9fa1e9db-b2a1-48ec-957c-e15da8597f62.JPG)

I will do some further tests with it later on, but that looks to be doing what I need, so thanks a lot.

I guess I will close this now? I'm not really sure what is the S.O.P. with GutHub issues.

**Comment by LenAnderson** [comment]
Cool! :)  
Thanks for all the the feedback.

Yea, looks like this issue can be closed.
